import React, { useContext, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import DataContext from './DataContext';
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from './ui/card';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import copy from 'copy-to-clipboard';
import { Button } from "./ui/button"
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "./ui/form"
import { Input } from "./ui/input"
import { Checkbox } from "./ui/checkbox"

export default function EvaluatorInputForm() {
  const { systems, evaluators } = useContext(DataContext);

  const evaluatorSchema = z.object({
    id: z.string().refine((id) => !evaluators.some(system => system.id === id), {
      message: "ID must be unique among evaluators",
    }),
    name: z.string(),
    role: z.string(),
    URL: z.string().url(),
    conflict: z.array(z.string()).optional()
  });


  const form = useForm<z.infer<typeof evaluatorSchema>>({
    resolver: zodResolver(evaluatorSchema),
    mode: "onChange", // Use "onChange" mode for real-time validation feedback
  });

  const { watch, setValue, trigger, formState: { errors } } = form;
  // Watch values outside of the render function
  const evaluatorUrl = watch("URL");
  useEffect(() => {  
    let evaluatorIdentifier = '{identifier_from_url}';
    if (evaluatorUrl) {
      if (evaluatorUrl.includes("twitter")) {
        evaluatorIdentifier = evaluatorUrl.split("/")[3].toLowerCase();
      } else if (evaluatorUrl.includes("wikipedia")) {
        evaluatorIdentifier = evaluatorUrl.split("/")[-1].toLowerCase();
      }
    }
    if (evaluatorIdentifier) {
      setValue("id", evaluatorIdentifier);
    }
    trigger("id")
  }, [evaluatorUrl, setValue, trigger]);


  function onSubmit(values: z.infer<typeof evaluatorSchema>) {
    copy(JSON.stringify(values, null, 2));
    alert("Data copied to clipboard!");
    console.log(values)
  }

  return (
    <Card>
      <CardHeader>
          <CardTitle className="text-xl font-bold">New Evaluator</CardTitle>
      </CardHeader>
      <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-2">
              {/* ID Field */}
        <FormField
          control={form.control}
          name="id"
          render={({ field }) => (
            <FormItem>
              <FormLabel>id</FormLabel>
              <FormControl>
                <Input
                  {...form.register("id")}
                  className={`bg-gray-200 ${errors.id ? 'border-red-500' : ''}`}
                  onChange={(e) => {
                    setValue("id", e.target.value.toLowerCase().replace(/\s+/g, '-'));
                    trigger("id");
                  }}
                />
              </FormControl>
              <FormDescription>
                Generated by rule. Unique identifier for the evaluator.<br></br>Defaults to the Twitter username or Wikipedia URL ending.
              </FormDescription>
              {errors.id && <FormMessage>{errors.id.message?.toString()}</FormMessage>}
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="name"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Name</FormLabel>
              <FormControl>
                <Input {...field} />
              </FormControl>
              <FormDescription>
              </FormDescription>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="role"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Role</FormLabel>
              <FormControl>
                <Input {...field} />
              </FormControl>
              <FormDescription>
              </FormDescription>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="URL"
          render={({ field }) => (
            <FormItem>
              <FormLabel>URL</FormLabel>
              <FormControl>
                <Input {...field} />
              </FormControl>
              <FormDescription>
                URL as reference for evaluator. Please default to an authoritative URL.
              </FormDescription>
              <FormMessage />
            </FormItem>
          )}
        />
        <hr></hr><FormLabel>Conflict (Optional)</FormLabel>
        {systems.map((system) => (
          <FormField
            key={system.id}
            control={form.control}
            name="conflict"
            render={({ field }) => {
              return (
                <FormItem
                  key={system.id}
                  className="flex flex-row systems-start items-center space-x-1 space-y-1"
                >
                  <FormControl>
                    <Checkbox
                      checked={field.value?.includes(system.id)}
                      onCheckedChange={(checked) => {
                        return checked
                          ? field.onChange([...(field.value || []), system.id])
                          : field.onChange(
                            (field.value || []).filter(
                              (value) => value !== system.id
                            )
                          )
                      }}
                    />
                  </FormControl>
                  <FormLabel className="text-sm font-normal">{system.name}</FormLabel>
                </FormItem>
              )
            }}
          />))}
              <Button type="submit">Submit</Button>
            </form>
          </Form>
      </CardContent>
    </Card>
  )
}